spring:
  #Resource server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mini-project-2

# Keycloak configuration
keycloak:
  realm: mini-project-2
  resource: mini-project-2
  auth-server-url: http://localhost:8080/
  credentials:
    secret: SqcvlCvXfpC5Gv0BKJnsJNau9c6Q78e1
    client-id: mini-project-2
    provider: secret
# Swagger configuration
springdoc:
  swagger-ui:
    oauth:
      client-id: mini-project-2
      client-secret: SqcvlCvXfpC5Gv0BKJnsJNau9c6Q78e1
      realm: mini-project-2
